# Auto-generated by canto because you don't have one.
# Please copy to/create ~/.canto/conf.py
from canto.extra import *
import os

if os.getenv("TERM") == "linux":
    link_handler("w3m \"%u\"", text=True)
    image_handler("sudo fbi \"%u\"", text=True, fetch=True)
else:
    link_handler("w3m \"%u\"", text=True)
    image_handler("eog \"%u\"", fetch=True)
    colors[0] = (123, "default")


keys['/'] = search_filter
keys['y'] = yank

filters=[show_unread, None]
default_tag_sorts([by_unread])

add("http://www.engadget.com/rss.xml",tags=[None,"Tech"])
